### ISSUE TITLE
数据不能初始化

### ISSUE THREAD

**Issue by mxyqsh** [PaddleCV-SIG/GeoView#74]
数据库paddle_rs不为空，不进行初始化操作
数据需要什么格式

**Comment by jscslld** [comment]
如果是第一次启动，将paddle_rs数据库清空即可。如果不是第一次启动，忽略这个提示。


卢利栋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddleCV-SIG/GeoView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月28日(星期五) 下午4:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PaddleCV-SIG/GeoView] 数据不能初始化 (Issue #74)





 
数据库paddle_rs不为空，不进行初始化操作
 数据需要什么格式

**Comment by mxyqsh** [comment]
好的好的
Can not import `map_display`. This is probably because GDAL is not properly installed. 也是可以忽略的吗

**Comment by jscslld** [comment]
如果不影响使用，可以忽略，这个库是用来对一些图片格式进行处理的。如果使用时出现了异常，可以考虑安装GDAL，Windows下建议按https://blog.csdn.net/wokaowokaowokao12345/article/details/129011091教程的方法二进行安装，成功率比较高。Linux下直接pip install一般就可以了。




卢利栋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddleCV-SIG/GeoView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月28日(星期五) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddleCV-SIG/GeoView] 数据不能初始化 (Issue #74)





 
好的好的
 Can not import map_display. This is probably because GDAL is not properly installed. 也是可以忽略的吗

**Comment by mxyqsh** [comment]
好的 感谢感谢！！！

**Comment by mxyqsh** [comment]
我在测试地物分类的时候，后台报错。
Cannot find raw_params. Default arguments will be used to construct the model.

**Comment by mxyqsh** [comment]
![2023-07-28 17-48-03屏幕截图](https://github.com/PaddleCV-SIG/GeoView/assets/54066148/799da6fb-804b-4f79-beb8-6236b0f030b0)

**Comment by jscslld** [comment]
这个应该不影响，我看推理结果应该是正常出来了吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月28日(周五) 下午5:49
收件人: ***@***.***&gt;;
抄送: "Lu ***@***.******@***.***&gt;;
主题: Re: [PaddleCV-SIG/GeoView] 数据不能初始化 (Issue #74)

**Comment by mxyqsh** [comment]
![2023-07-28 17-54-58屏幕截图](https://github.com/PaddleCV-SIG/GeoView/assets/54066148/fe8872fd-2a36-4f52-984c-3d9f89355d3a)

**Comment by jscslld** [comment]
我们在develop分支下面修复了未捕获异常的问题，您更新下develop分支的最新版本试试

**Comment by mxyqsh** [comment]
可正常运行啦  
谢谢
